export async function seed(knex): Promise<void> {
   // Deletes ALL existing entries
   await knex("commune").del();

   // Inserts seed entries
   await knex('commune').insert([
      { province_id: '1', city_id: '4', name: 'Belize' },
      { province_id: '1', city_id: '4', name: 'Miconje' },
      { province_id: '1', city_id: '4', name: 'Luali' },
      { province_id: '1', city_id: '3', name: 'Buco Zau' },
      { province_id: '1', city_id: '3', name: 'Necuto' },
      { province_id: '1', city_id: '3', name: 'Inhuca' },
      { province_id: '1', city_id: '1', name: 'Cabinda' },
      { province_id: '1', city_id: '1', name: 'Malembo' },
      { province_id: '1', city_id: '1', name: 'Tando Zinze' },
      { province_id: '1', city_id: '2', name: 'Cacongo' },
      { province_id: '1', city_id: '2', name: 'Dinge' },
      { province_id: '1', city_id: '2', name: 'Massabi' },
      { province_id: '2', city_id: '9', name: 'Cuimba' },
      { province_id: '2', city_id: '9', name: 'Buela' },
      { province_id: '2', city_id: '9', name: 'Serra da Canda' },
      { province_id: '2', city_id: '9', name: 'Luvaca' },
      { province_id: '2', city_id: '6', name: 'Mbanza Kongo' },
      { province_id: '2', city_id: '6', name: 'Luvo' },
      { province_id: '2', city_id: '6', name: 'Caluca' },
      { province_id: '2', city_id: '6', name: 'Madimba' },
      { province_id: '2', city_id: '6', name: 'Quiende' },
      { province_id: '2', city_id: '6', name: 'Calambata' },
      { province_id: '2', city_id: '10', name: 'Nóqui' },
      { province_id: '2', city_id: '10', name: 'Lufico' },
      { province_id: '2', city_id: '10', name: 'Mpala' },
      { province_id: '2', city_id: '7', name: 'Nzeto' },
      { province_id: '2', city_id: '7', name: 'Quindeje' },
      { province_id: '2', city_id: '7', name: 'Musserra' },
      { province_id: '2', city_id: '7', name: 'Quibala Norte' },
      { province_id: '2', city_id: '5', name: 'Soyo' },
      { province_id: '2', city_id: '5', name: 'Sumba' },
      { province_id: '2', city_id: '5', name: 'Pedra de Feitiço' },
      { province_id: '2', city_id: '5', name: 'Quêlo' },
      { province_id: '2', city_id: '5', name: 'Mangue Grande' },
      { province_id: '2', city_id: '8', name: 'Tomboco' },
      { province_id: '2', city_id: '8', name: 'Quinsimba' },
      { province_id: '2', city_id: '8', name: 'Quinzau' },
      { province_id: '3', city_id: '23', name: 'Cangola' },
      { province_id: '3', city_id: '23', name: 'Bengo' },
      { province_id: '3', city_id: '23', name: 'Caiongo' },
      { province_id: '3', city_id: '13', name: 'Nova Ambuíla' },
      { province_id: '3', city_id: '13', name: 'Quipedro' },
      { province_id: '3', city_id: '19', name: 'Bembe' },
      { province_id: '3', city_id: '19', name: 'Lucunga' },
      { province_id: '3', city_id: '19', name: 'Mabaia' },
      { province_id: '3', city_id: '26', name: 'Buenga Sul' },
      { province_id: '3', city_id: '26', name: 'Nova Esperança' },
      { province_id: '3', city_id: '26', name: 'Cuilo Camboso' },
      { province_id: '3', city_id: '17', name: 'Damba' },
      { province_id: '3', city_id: '17', name: 'Nsosso' },
      { province_id: '3', city_id: '17', name: 'Camatambo' },
      { province_id: '3', city_id: '17', name: 'Lêmboa' },
      { province_id: '3', city_id: '17', name: 'Petecusso' },
      { province_id: '3', city_id: '11', name: 'Quitexe' },
      { province_id: '3', city_id: '11', name: 'Aldeia Viçosa' },
      { province_id: '3', city_id: '11', name: 'Cambamba' },
      { province_id: '3', city_id: '11', name: 'Vista Alegre' },
      { province_id: '3', city_id: '16', name: 'Maquela do Zombo' },
      { province_id: '3', city_id: '16', name: 'Quibocolo' },
      { province_id: '3', city_id: '16', name: 'Béu' },
      { province_id: '3', city_id: '16', name: 'Sacandica' },
      { province_id: '3', city_id: '16', name: 'Cuilo Futa' },
      { province_id: '3', city_id: '20', name: 'Macocola' },
      { province_id: '3', city_id: '20', name: 'Macolo' },
      { province_id: '3', city_id: '20', name: 'Milunga' },
      { province_id: '3', city_id: '20', name: 'Massau' },
      { province_id: '3', city_id: '25', name: 'Mucaba' },
      { province_id: '3', city_id: '25', name: 'Uando Mucaba' },
      { province_id: '3', city_id: '14', name: 'Dimuca' },
      { province_id: '3', city_id: '14', name: 'Quisseque' },
      { province_id: '3', city_id: '14', name: 'Negage' },
      { province_id: '3', city_id: '18', name: 'Sanza Pombo' },
      { province_id: '3', city_id: '18', name: 'Cuilo Pombo' },
      { province_id: '3', city_id: '18', name: 'Uamba' },
      { province_id: '3', city_id: '18', name: 'Alfândega' },
      { province_id: '3', city_id: '22', name: 'Cuango' },
      { province_id: '3', city_id: '22', name: 'Icoca' },
      { province_id: '3', city_id: '22', name: 'Quimbele' },
      { province_id: '3', city_id: '22', name: 'Alto Zaza' },
      { province_id: '3', city_id: '21', name: 'Songo' },
      { province_id: '3', city_id: '21', name: 'Quivuenga' },
      { province_id: '4', city_id: '31', name: 'Ambriz' },
      { province_id: '4', city_id: '31', name: 'Bela Vista' },
      { province_id: '4', city_id: '31', name: 'Tabi' },
      { province_id: '4', city_id: '30', name: 'Bula Atumba' },
      { province_id: '4', city_id: '30', name: 'Quiage' },
      { province_id: '4', city_id: '27', name: 'Barra do Dande' },
      { province_id: '4', city_id: '27', name: 'Caxito' },
      { province_id: '4', city_id: '27', name: 'Mabubas' },
      { province_id: '4', city_id: '27', name: 'Quicabo' },
      { province_id: '4', city_id: '27', name: 'Úcua' },
      { province_id: '4', city_id: '28', name: 'Quibaxe' },
      { province_id: '4', city_id: '28', name: 'Piri' },
      { province_id: '4', city_id: '28', name: 'Paredes' },
      { province_id: '4', city_id: '28', name: 'Coxe' },
      { province_id: '4', city_id: '29', name: 'Canacassala' },
      { province_id: '4', city_id: '29', name: 'Quicunzo' },
      { province_id: '4', city_id: '29', name: 'Muxaluando' },
      { province_id: '4', city_id: '29', name: 'Quixico' },
      { province_id: '4', city_id: '29', name: 'Gombe' },
      { province_id: '4', city_id: '29', name: 'Cage' },
      { province_id: '4', city_id: '29', name: 'Zala' },
      { province_id: '4', city_id: '32', name: 'Pango Aluquém' },
      { province_id: '4', city_id: '32', name: 'Cazuangongo' },
      { province_id: '5', city_id: '39', name: 'Barra do Cuanza' },
      { province_id: '5', city_id: '36', name: 'Funda' },
      { province_id: '5', city_id: '34', name: 'Cassoneca' },
      { province_id: '5', city_id: '34', name: 'Cabiri' },
      { province_id: '5', city_id: '34', name: 'Bom Jesus' },
      { province_id: '5', city_id: '34', name: 'Caculo Cahango' },
      { province_id: '5', city_id: '34', name: 'Quiminha' },
      { province_id: '5', city_id: '35', name: 'Muxima' },
      { province_id: '5', city_id: '35', name: 'Demba Chio' },
      { province_id: '5', city_id: '35', name: 'Quixinge' },
      { province_id: '5', city_id: '35', name: 'Mumbondo' },
      { province_id: '5', city_id: '35', name: 'Cabo Ledo' },
      { province_id: '5', city_id: '40', name: 'Mussulo' },
      { province_id: '5', city_id: '38', name: 'Calumbo' },
      { province_id: '6', city_id: '46', name: 'Camabatela' },
      { province_id: '6', city_id: '46', name: 'Tango' },
      { province_id: '6', city_id: '46', name: 'Máua' },
      { province_id: '6', city_id: '46', name: 'Bindo' },
      { province_id: '6', city_id: '46', name: 'Luinga' },
      { province_id: '6', city_id: '48', name: 'Banga' },
      { province_id: '6', city_id: '48', name: 'Caculo Cabaça' },
      { province_id: '6', city_id: '48', name: 'Aldeia Nova' },
      { province_id: '6', city_id: '48', name: 'Cariamba' },
      { province_id: '6', city_id: '49', name: 'Bolongongo' },
      { province_id: '6', city_id: '49', name: 'Terreiro' },
      { province_id: '6', city_id: '49', name: 'Quiquiemba' },
      { province_id: '6', city_id: '44', name: 'Dondo' },
      { province_id: '6', city_id: '44', name: 'Massangano' },
      { province_id: '6', city_id: '44', name: 'Dange ya Menha' },
      { province_id: '6', city_id: '44', name: 'Zenza do Itombe' },
      { province_id: '6', city_id: '44', name: 'São Pedro da Quilemba' },
      { province_id: '6', city_id: '42', name: 'Ndalatando' },
      { province_id: '6', city_id: '42', name: 'Canhoca' },
      { province_id: '6', city_id: '43', name: 'Golungo Alto' },
      { province_id: '6', city_id: '43', name: 'Cambondo' },
      { province_id: '6', city_id: '43', name: 'Cêrca' },
      { province_id: '6', city_id: '43', name: 'Quiluanje' },
      { province_id: '6', city_id: '47', name: 'Lucala' },
      { province_id: '6', city_id: '47', name: 'Quiangombe' },
      { province_id: '6', city_id: '51', name: 'Quilombo dos Dembos' },
      { province_id: '6', city_id: '51', name: 'Camame' },
      { province_id: '6', city_id: '51', name: 'Cavunga' },
      { province_id: '6', city_id: '45', name: 'Samba Cajú' },
      { province_id: '6', city_id: '45', name: 'Samba Lucala' },
      { province_id: '7', city_id: '54', name: 'Gabela' },
      { province_id: '7', city_id: '54', name: 'Assango' },
      { province_id: '7', city_id: '55', name: 'Cassongue' },
      { province_id: '7', city_id: '55', name: 'Pambangala' },
      { province_id: '7', city_id: '55', name: 'Dumbi' },
      { province_id: '7', city_id: '55', name: 'Atóme' },
      { province_id: '7', city_id: '59', name: 'Sanga' },
      { province_id: '7', city_id: '59', name: 'Waku Kungo' },
      { province_id: '7', city_id: '59', name: 'Quissanga Cunjo' },
      { province_id: '7', city_id: '63', name: 'Conda' },
      { province_id: '7', city_id: '63', name: 'Cunjo' },
      { province_id: '7', city_id: '62', name: 'Ebo' },
      { province_id: '7', city_id: '62', name: 'Condé' },
      { province_id: '7', city_id: '62', name: 'Quissanje' },
      { province_id: '7', city_id: '53', name: 'Calulo' },
      { province_id: '7', city_id: '53', name: 'Munenga' },
      { province_id: '7', city_id: '53', name: 'Cabuta' },
      { province_id: '7', city_id: '53', name: 'Quissongo' },
      { province_id: '7', city_id: '60', name: 'Mussende' },
      { province_id: '7', city_id: '60', name: 'Quienha' },
      { province_id: '7', city_id: '60', name: 'São Lucas' },
      { province_id: '7', city_id: '56', name: 'Porto Amboim' },
      { province_id: '7', city_id: '56', name: 'Capolo' },
      { province_id: '7', city_id: '57', name: 'Quibala' },
      { province_id: '7', city_id: '57', name: 'Dala Cachibo' },
      { province_id: '7', city_id: '57', name: 'Cariango' },
      { province_id: '7', city_id: '57', name: 'Lonhe' },
      { province_id: '7', city_id: '61', name: 'Quilenda' },
      { province_id: '7', city_id: '61', name: 'Quirimbo' },
      { province_id: '7', city_id: '58', name: 'Seles' },
      { province_id: '7', city_id: '58', name: 'Amboiva' },
      { province_id: '7', city_id: '58', name: 'Botera' },
      { province_id: '7', city_id: '52', name: 'Sumbe' },
      { province_id: '7', city_id: '52', name: 'Gungo' },
      { province_id: '7', city_id: '52', name: 'Gangula' },
      { province_id: '7', city_id: '52', name: 'Quicombo' },
      { province_id: '8', city_id: '67', name: 'Massango' },
      { province_id: '8', city_id: '67', name: 'Quihuhu' },
      { province_id: '8', city_id: '67', name: 'Quinguengue' },
      { province_id: '8', city_id: '66', name: 'Cacuso' },
      { province_id: '8', city_id: '66', name: 'Lombe' },
      { province_id: '8', city_id: '66', name: 'Quizenga' },
      { province_id: '8', city_id: '66', name: 'Pungu a Ndongo' },
      { province_id: '8', city_id: '66', name: 'Soqueco' },
      { province_id: '8', city_id: '72', name: 'Mbanji ya Ngola' },
      { province_id: '8', city_id: '72', name: 'Cahombo' },
      { province_id: '8', city_id: '72', name: 'Cambo Suinginge' },
      { province_id: '8', city_id: '72', name: 'Micanda' },
      { province_id: '8', city_id: '64', name: 'Calandula' },
      { province_id: '8', city_id: '64', name: 'Cateco Cangola' },
      { province_id: '8', city_id: '64', name: 'Cota' },
      { province_id: '8', city_id: '64', name: 'Cuale' },
      { province_id: '8', city_id: '64', name: 'Quinje' },
      { province_id: '8', city_id: '74', name: 'Talamungongo' },
      { province_id: '8', city_id: '74', name: 'Cambundi Catembo' },
      { province_id: '8', city_id: '74', name: 'Quitapa' },
      { province_id: '8', city_id: '74', name: 'Dumba Cambango' },
      { province_id: '8', city_id: '71', name: 'Cangandala' },
      { province_id: '8', city_id: '71', name: 'Bembo' },
      { province_id: '8', city_id: '71', name: 'Culamagia' },
      { province_id: '8', city_id: '71', name: 'Caribo' },
      { province_id: '8', city_id: '76', name: 'Kiwaba Nzoji' },
      { province_id: '8', city_id: '76', name: 'Mufuma' },
      { province_id: '8', city_id: '73', name: 'Kunda dya Baze' },
      { province_id: '8', city_id: '73', name: 'Milando' },
      { province_id: '8', city_id: '73', name: 'Lemba' },
      { province_id: '8', city_id: '77', name: 'Quimbango' },
      { province_id: '8', city_id: '77', name: 'Capunda' },
      { province_id: '8', city_id: '77', name: 'Dombo wa Zanga' },
      { province_id: '8', city_id: '77', name: 'Luquembo' },
      { province_id: '8', city_id: '77', name: 'Cunga Palanga' },
      { province_id: '8', city_id: '77', name: 'Rimba' },
      { province_id: '8', city_id: '65', name: 'Malanje' },
      { province_id: '8', city_id: '65', name: 'Ngola Luiji' },
      { province_id: '8', city_id: '65', name: 'Cambaxe' },
      { province_id: '8', city_id: '68', name: 'Lutembo' },
      { province_id: '8', city_id: '68', name: 'Chiume' },
      { province_id: '8', city_id: '68', name: 'Lumbala Nguimbo' },
      { province_id: '8', city_id: '75', name: 'Catala' },
      { province_id: '8', city_id: '75', name: 'Caculama' },
      { province_id: '8', city_id: '75', name: 'Caxinga' },
      { province_id: '8', city_id: '75', name: 'Muquixe' },
      { province_id: '8', city_id: '69', name: 'Quela' },
      { province_id: '8', city_id: '69', name: 'Xandel' },
      { province_id: '8', city_id: '69', name: 'Moma' },
      { province_id: '8', city_id: '69', name: 'Bângalas' },
      { province_id: '8', city_id: '70', name: 'Sautar' },
      { province_id: '8', city_id: '70', name: 'Quirima' },
      { province_id: '9', city_id: '85', name: 'Luia' },
      { province_id: '9', city_id: '85', name: 'Cachimo' },
      { province_id: '9', city_id: '85', name: 'Canzar' },
      { province_id: '9', city_id: '85', name: 'Cambulo' },
      { province_id: '9', city_id: '82', name: 'Capenda Camulemba' },
      { province_id: '9', city_id: '82', name: 'Xinge' },
      { province_id: '9', city_id: '79', name: 'Camaxilo' },
      { province_id: '9', city_id: '79', name: 'Caungula' },
      { province_id: '9', city_id: '80', name: 'Chitato' },
      { province_id: '9', city_id: '80', name: 'Luachimo' },
      { province_id: '9', city_id: '83', name: 'Cuango' },
      { province_id: '9', city_id: '83', name: 'Luremo' },
      { province_id: '9', city_id: '78', name: 'Cuilo' },
      { province_id: '9', city_id: '78', name: 'Caluango' },
      { province_id: '9', city_id: '81', name: 'Lubalo' },
      { province_id: '9', city_id: '81', name: 'Luangue' },
      { province_id: '9', city_id: '81', name: 'Muvuluege' },
      { province_id: '9', city_id: '84', name: 'Lucapa' },
      { province_id: '9', city_id: '84', name: 'Capaia' },
      { province_id: '9', city_id: '84', name: 'Camissombo' },
      { province_id: '9', city_id: '84', name: 'Xá Cassau' },
      { province_id: '9', city_id: '86', name: 'Xá Muteba' },
      { province_id: '9', city_id: '86', name: 'Longo' },
      { province_id: '9', city_id: '86', name: 'Cassanje Calucala' },
      { province_id: '10', city_id: '90', name: 'Xassengue' },
      { province_id: '10', city_id: '90', name: 'Cucumbi' },
      { province_id: '10', city_id: '90', name: 'Alto Chicapa' },
      { province_id: '10', city_id: '90', name: 'Cacolo' },
      { province_id: '10', city_id: '91', name: 'Dala' },
      { province_id: '10', city_id: '91', name: 'Luma Cassai' },
      { province_id: '10', city_id: '91', name: 'Cazage' },
      { province_id: '10', city_id: '89', name: 'Chiluage' },
      { province_id: '10', city_id: '89', name: 'Cassai' },
      { province_id: '10', city_id: '89', name: 'Muriege' },
      { province_id: '10', city_id: '89', name: 'Muconda' },
      { province_id: '10', city_id: '88', name: 'Saurimo' },
      { province_id: '10', city_id: '88', name: 'Mona Quimbundo' },
      { province_id: '10', city_id: '88', name: 'Sombo' },
      { province_id: '11', city_id: '94', name: 'Nana Candundo' },
      { province_id: '11', city_id: '94', name: 'Lumbala Caquengue' },
      { province_id: '11', city_id: '94', name: 'Cazombo' },
      { province_id: '11', city_id: '94', name: 'Macondo' },
      { province_id: '11', city_id: '94', name: 'Caianda' },
      { province_id: '11', city_id: '94', name: 'Calunda' },
      { province_id: '11', city_id: '94', name: 'Lóvua' },
      { province_id: '11', city_id: '95', name: 'Lutembo' },
      { province_id: '11', city_id: '95', name: 'Chiume' },
      { province_id: '11', city_id: '95', name: 'Lumbala Nguimbo' },
      { province_id: '11', city_id: '95', name: 'Luvuei' },
      { province_id: '11', city_id: '95', name: 'Ninda' },
      { province_id: '11', city_id: '95', name: 'Mussuma' },
      { province_id: '11', city_id: '95', name: 'Sessa' },
      { province_id: '11', city_id: '100', name: 'Léua' },
      { province_id: '11', city_id: '100', name: 'Liangongo' },
      { province_id: '11', city_id: '96', name: 'Luacano' },
      { province_id: '11', city_id: '96', name: 'Lago Dilolo' },
      { province_id: '11', city_id: '93', name: 'Cangombe' },
      { province_id: '11', city_id: '93', name: 'Cassamba' },
      { province_id: '11', city_id: '93', name: 'Tempué' },
      { province_id: '11', city_id: '93', name: 'Cangamba' },
      { province_id: '11', city_id: '93', name: 'Muié' },
      { province_id: '11', city_id: '92', name: 'Lucusse' },
      { province_id: '11', city_id: '92', name: 'Cachipoque' },
      { province_id: '11', city_id: '92', name: 'Luena' },
      { province_id: '11', city_id: '92', name: 'Muangai' },
      { province_id: '12', city_id: '101', name: 'Andulo' },
      { province_id: '12', city_id: '101', name: 'Calucinga' },
      { province_id: '12', city_id: '101', name: 'Cassumbe' },
      { province_id: '12', city_id: '101', name: 'Chivaúlo' },
      { province_id: '12', city_id: '104', name: 'Camacupa' },
      { province_id: '12', city_id: '104', name: 'Ringoma' },
      { province_id: '12', city_id: '104', name: 'Muinha' },
      { province_id: '12', city_id: '104', name: 'Umpulo' },
      { province_id: '12', city_id: '104', name: 'Cuanza' },
      { province_id: '12', city_id: '106', name: 'Catabola' },
      { province_id: '12', city_id: '106', name: 'Chipeta' },
      { province_id: '12', city_id: '106', name: 'Caiuera' },
      { province_id: '12', city_id: '106', name: 'Chiuca' },
      { province_id: '12', city_id: '106', name: 'Sande' },
      { province_id: '12', city_id: '105', name: 'Chinguar' },
      { province_id: '12', city_id: '105', name: 'Cutato' },
      { province_id: '12', city_id: '105', name: 'Cangote' },
      { province_id: '12', city_id: '102', name: 'Chitembo' },
      { province_id: '12', city_id: '102', name: 'Cachingues' },
      { province_id: '12', city_id: '102', name: 'Mutumbo' },
      { province_id: '12', city_id: '102', name: 'Mumbué' },
      { province_id: '12', city_id: '102', name: 'Malengue' },
      { province_id: '12', city_id: '102', name: 'Soma Cuanza' },
      { province_id: '12', city_id: '108', name: 'Cuemba' },
      { province_id: '12', city_id: '108', name: 'Luando' },
      { province_id: '12', city_id: '108', name: 'Munhango' },
      { province_id: '12', city_id: '108', name: 'Sachinemuna' },
      { province_id: '12', city_id: '103', name: 'Cuito' },
      { province_id: '12', city_id: '103', name: 'Chicala' },
      { province_id: '12', city_id: '103', name: 'Cunje' },
      { province_id: '12', city_id: '103', name: 'Trumba' },
      { province_id: '12', city_id: '103', name: 'Cambândua' },
      { province_id: '12', city_id: '107', name: 'Cunhinga' },
      { province_id: '12', city_id: '107', name: 'Belo Horizonte' },
      { province_id: '12', city_id: '109', name: 'Nharêa' },
      { province_id: '12', city_id: '109', name: 'Gamba' },
      { province_id: '12', city_id: '109', name: 'Lúbia' },
      { province_id: '12', city_id: '109', name: 'Caiei' },
      { province_id: '12', city_id: '109', name: 'Dando' },
      { province_id: '13', city_id: '110', name: 'Bimbe' },
      { province_id: '13', city_id: '110', name: 'Bailundo' },
      { province_id: '13', city_id: '110', name: 'Lunge' },
      { province_id: '13', city_id: '110', name: 'Luvemba' },
      { province_id: '13', city_id: '110', name: 'Hengue' },
      { province_id: '13', city_id: '113', name: 'Caála' },
      { province_id: '13', city_id: '113', name: 'Catata' },
      { province_id: '13', city_id: '113', name: 'Calenga' },
      { province_id: '13', city_id: '113', name: 'Cuima' },
      { province_id: '13', city_id: '115', name: 'Chiumbo' },
      { province_id: '13', city_id: '115', name: 'Chinhama' },
      { province_id: '13', city_id: '115', name: 'Cachiungo' },
      { province_id: '13', city_id: '114', name: 'Sambo' },
      { province_id: '13', city_id: '114', name: 'Mbawe' },
      { province_id: '13', city_id: '114', name: 'Chicala' },
      { province_id: '13', city_id: '114', name: 'Samboto' },
      { province_id: '13', city_id: '120', name: 'Chinjenje' },
      { province_id: '13', city_id: '120', name: 'Chiaca' },
      { province_id: '13', city_id: '119', name: 'Quipeio' },
      { province_id: '13', city_id: '119', name: 'Ecunha' },
      { province_id: '13', city_id: '111', name: 'Huambo' },
      { province_id: '13', city_id: '111', name: 'Calima' },
      { province_id: '13', city_id: '111', name: 'Chipipa' },
      { province_id: '13', city_id: '112', name: 'Londuimbali' },
      { province_id: '13', city_id: '112', name: 'Cumbira' },
      { province_id: '13', city_id: '112', name: 'Galanga' },
      { province_id: '13', city_id: '112', name: 'Ussoque' },
      { province_id: '13', city_id: '112', name: 'Alto Hama' },
      { province_id: '13', city_id: '117', name: 'Lépi' },
      { province_id: '13', city_id: '117', name: 'Iava' },
      { province_id: '13', city_id: '117', name: 'Chilata' },
      { province_id: '13', city_id: '117', name: 'Longonjo' },
      { province_id: '13', city_id: '116', name: 'Mungo' },
      { province_id: '13', city_id: '116', name: 'Cambuengo' },
      { province_id: '13', city_id: '118', name: 'Ucuma' },
      { province_id: '13', city_id: '118', name: 'Cacoma' },
      { province_id: '13', city_id: '118', name: 'Mundundo' },
      { province_id: '14', city_id: '128', name: 'Baía Farta' },
      { province_id: '14', city_id: '128', name: 'Dombe Grande' },
      { province_id: '14', city_id: '128', name: 'Calohanga' },
      { province_id: '14', city_id: '128', name: 'Equimina' },
      { province_id: '14', city_id: '126', name: 'Balombo' },
      { province_id: '14', city_id: '126', name: 'Chingongo' },
      { province_id: '14', city_id: '126', name: 'Chindumbo' },
      { province_id: '14', city_id: '126', name: 'Maca Mombolo' },
      { province_id: '14', city_id: '125', name: 'Bocoio' },
      { province_id: '14', city_id: '125', name: 'Cubal do Lumbo' },
      { province_id: '14', city_id: '125', name: 'Monte Belo' },
      { province_id: '14', city_id: '125', name: 'Chila' },
      { province_id: '14', city_id: '125', name: 'Passe' },
      { province_id: '14', city_id: '129', name: 'Caimbambo' },
      { province_id: '14', city_id: '129', name: 'Catengue' },
      { province_id: '14', city_id: '129', name: 'Caiave' },
      { province_id: '14', city_id: '129', name: 'Canhamela' },
      { province_id: '14', city_id: '129', name: 'Viangombe' },
      { province_id: '14', city_id: '124', name: 'Catumbela' },
      { province_id: '14', city_id: '124', name: 'Biópio' },
      { province_id: '14', city_id: '124', name: 'Gama' },
      { province_id: '14', city_id: '124', name: 'Praia Bebé' },
      { province_id: '14', city_id: '130', name: 'Chongorói' },
      { province_id: '14', city_id: '130', name: 'Bolonguera' },
      { province_id: '14', city_id: '130', name: 'Camuine' },
      { province_id: '14', city_id: '127', name: 'Cubal' },
      { province_id: '14', city_id: '127', name: 'Capupa' },
      { province_id: '14', city_id: '127', name: 'Tumbulo' },
      { province_id: '14', city_id: '127', name: 'Lambala' },
      { province_id: '14', city_id: '122', name: 'Ganda' },
      { province_id: '14', city_id: '122', name: 'Ebanga' },
      { province_id: '14', city_id: '122', name: 'Chicuma' },
      { province_id: '14', city_id: '122', name: 'Babaera' },
      { province_id: '14', city_id: '122', name: 'Casseque' },
      { province_id: '14', city_id: '123', name: 'Lobito' },
      { province_id: '14', city_id: '123', name: 'Egito Praia' },
      { province_id: '14', city_id: '123', name: 'Canata' },
      { province_id: '14', city_id: '123', name: 'Canjala' },
      { province_id: '15', city_id: '133', name: 'Bibala' },
      { province_id: '15', city_id: '133', name: 'Caitou' },
      { province_id: '15', city_id: '133', name: 'Capangombe' },
      { province_id: '15', city_id: '133', name: 'Lola' },
      { province_id: '15', city_id: '135', name: 'Camucuio' },
      { province_id: '15', city_id: '135', name: 'Mamué' },
      { province_id: '15', city_id: '135', name: 'Chingo' },
      { province_id: '15', city_id: '131', name: 'Moçâmedes' },
      { province_id: '15', city_id: '131', name: 'Lucira' },
      { province_id: '15', city_id: '131', name: 'Bentiaba' },
      { province_id: '15', city_id: '131', name: 'Forte Santa Rita' },
      { province_id: '15', city_id: '132', name: 'Baía dos Tigres' },
      { province_id: '15', city_id: '132', name: 'Iona' },
      { province_id: '15', city_id: '132', name: 'Tômbwa' },
      { province_id: '15', city_id: '134', name: 'Virei' },
      { province_id: '15', city_id: '134', name: 'Cainde' },
      { province_id: '16', city_id: '136', name: 'Caconda' },
      { province_id: '16', city_id: '136', name: 'Gungue' },
      { province_id: '16', city_id: '136', name: 'Uaba' },
      { province_id: '16', city_id: '136', name: 'Cusse' },
      { province_id: '16', city_id: '149', name: 'Chituto' },
      { province_id: '16', city_id: '149', name: 'Viti Vivali' },
      { province_id: '16', city_id: '149', name: 'Cacula' },
      { province_id: '16', city_id: '149', name: 'Tchicuaqueia' },
      { province_id: '16', city_id: '144', name: 'Caluquembe' },
      { province_id: '16', city_id: '144', name: 'Calepi' },
      { province_id: '16', city_id: '144', name: 'Ngola' },
      { province_id: '16', city_id: '142', name: 'Chibia' },
      { province_id: '16', city_id: '142', name: 'Jau' },
      { province_id: '16', city_id: '142', name: 'Capunda Cavilongo' },
      { province_id: '16', city_id: '142', name: 'Quihita' },
      { province_id: '16', city_id: '148', name: 'Chicomba' },
      { province_id: '16', city_id: '148', name: 'Cutenda' },
      { province_id: '16', city_id: '147', name: 'Bambi' },
      { province_id: '16', city_id: '147', name: 'Chipindo' },
      { province_id: '16', city_id: '140', name: 'Cuvango' },
      { province_id: '16', city_id: '140', name: 'Galangue' },
      { province_id: '16', city_id: '140', name: 'Vicungo' },
      { province_id: '16', city_id: '137', name: 'Chimbemba' },
      { province_id: '16', city_id: '137', name: 'Chiange' },
      { province_id: '16', city_id: '146', name: 'Dongo' },
      { province_id: '16', city_id: '146', name: 'Cassinga' },
      { province_id: '16', city_id: '146', name: 'Jamba' },
      { province_id: '16', city_id: '139', name: 'Lubango' },
      { province_id: '16', city_id: '139', name: 'Hoque' },
      { province_id: '16', city_id: '139', name: 'Arimba' },
      { province_id: '16', city_id: '139', name: 'Huila' },
      { province_id: '16', city_id: '145', name: 'Capelongo' },
      { province_id: '16', city_id: '145', name: 'Matala' },
      { province_id: '16', city_id: '145', name: 'Mulondo' },
      { province_id: '16', city_id: '143', name: 'Quilengues' },
      { province_id: '16', city_id: '143', name: 'Impulo' },
      { province_id: '16', city_id: '143', name: 'Dinde' },
      { province_id: '17', city_id: '150', name: 'Humpe' },
      { province_id: '17', city_id: '150', name: 'Mucope' },
      { province_id: '17', city_id: '150', name: 'Naulila' },
      { province_id: '17', city_id: '150', name: 'Ombala yo Mungu' },
      { province_id: '17', city_id: '150', name: 'Xangongo' },
      { province_id: '17', city_id: '151', name: 'Ondjiva' },
      { province_id: '17', city_id: '151', name: 'Nehone Cafima' },
      { province_id: '17', city_id: '151', name: 'Evale' },
      { province_id: '17', city_id: '151', name: 'Tchompolo Oximolo' },
      { province_id: '17', city_id: '151', name: 'Môngwa' },
      { province_id: '17', city_id: '152', name: 'Oncócua' },
      { province_id: '17', city_id: '152', name: 'Chitado' },
      { province_id: '17', city_id: '153', name: 'Cahama' },
      { province_id: '17', city_id: '153', name: 'Otchinjau' },
      { province_id: '17', city_id: '154', name: 'Mupa' },
      { province_id: '17', city_id: '154', name: 'Mukolongodjo' },
      { province_id: '17', city_id: '154', name: 'Calonga' },
      { province_id: '17', city_id: '154', name: 'Cubati' },
      { province_id: '17', city_id: '155', name: 'Namacunde' },
      { province_id: '17', city_id: '155', name: 'Chiede' },
      { province_id: '18', city_id: '162', name: 'Calai' },
      { province_id: '18', city_id: '162', name: 'Maué' },
      { province_id: '18', city_id: '162', name: 'Mavengue' },
      { province_id: '18', city_id: '163', name: 'Cuangar' },
      { province_id: '18', city_id: '163', name: 'Savate' },
      { province_id: '18', city_id: '163', name: 'Caila' },
      { province_id: '18', city_id: '160', name: 'Cuchi' },
      { province_id: '18', city_id: '160', name: 'Cutato' },
      { province_id: '18', city_id: '160', name: 'Chinguanja' },
      { province_id: '18', city_id: '160', name: 'Vissati' },
      { province_id: '18', city_id: '159', name: 'Cuito Cuanavale' },
      { province_id: '18', city_id: '159', name: 'Lupire' },
      { province_id: '18', city_id: '159', name: 'Longa' },
      { province_id: '18', city_id: '159', name: 'Baixo Longa' },
      { province_id: '18', city_id: '158', name: 'Dirico' },
      { province_id: '18', city_id: '158', name: 'Mucusso' },
      { province_id: '18', city_id: '158', name: 'Xamavera' },
      { province_id: '18', city_id: '157', name: 'Mavinga' },
      { province_id: '18', city_id: '157', name: 'Cutuile' },
      { province_id: '18', city_id: '157', name: 'Cunjamba' },
      { province_id: '18', city_id: '157', name: 'Luengue' },
      { province_id: '18', city_id: '156', name: 'Menongue' },
      { province_id: '18', city_id: '156', name: 'Caiundo' },
      { province_id: '18', city_id: '156', name: 'Cueio' },
      { province_id: '18', city_id: '156', name: 'Missombo' },
      { province_id: '18', city_id: '164', name: 'Nancova' },
      { province_id: '18', city_id: '164', name: 'Rito' },
      { province_id: '18', city_id: '161', name: 'Rivungo' },
      { province_id: '18', city_id: '161', name: 'Xipundo' },
      { province_id: '18', city_id: '161', name: 'Luiana' },      
   ]);
}